In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

ImportError: cannot import name 'display' from 'IPython.core.display' (C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\IPython\core\display.py)

In [ ]:
# got an error here, so running the next cell's code instead

In [2]:
from IPython.display import display, HTML

display(HTML("<style>.container { width:100% !important; }</style>"))

# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [4]:
%pip install pandas matplotlib scikit-learn

Collecting pandas
  Downloading pandas-3.0.2-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting matplotlib
  Downloading matplotlib-3.10.9-cp311-cp311-win_amd64.whl.metadata (52 kB)
     ---------------------------------------- 0.0/52.8 kB ? eta -:--:--
     ---------------------------------------- 0.0/52.8 kB ? eta -:--:--
     -------------------------------------- - 51.2/52.8 kB ? eta -:--:--
     -------------------------------------- - 51.2/52.8 kB ? eta -:--:--
     -------------------------------------- - 51.2/52.8 kB ? eta -:--:--
     -------------------------------------- - 51.2/52.8 kB ? eta -:--:--
     -------------------------------------- 52.8/52.8 kB 170.4 kB/s eta 0:00:00
Requirement already satisfied: scikit-learn in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.62.1-cp311-cp311-win_amd64.whl.metadata (119 kB)
     ---------------------------------------- 0.0/119.8 kB ? eta -:--:--
     ----------------------------------- -- 112.6/119.8 kB 6.4 MB/s eta 0:00:01
     -------------------------------------- 119.8/119.8 kB 2.3 MB/s eta 0:00:00
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp311-cp311-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\asus\appdata\roaming\python\python311\site-packages (from matplotlib) (26.0)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.2.0-cp311-cp311-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: scipy>=1.10.0 in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp311-cp311-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB 5.7 MB/s eta 0:00:02
   -- ------------------------------------- 0.5/9.9 MB 4.7 MB/s eta 0:00:02
   --- ------------------------------------ 0.7/9.9 MB 4.7 MB/s eta 0:00:02
   --- ------------------------------------ 0.9/9.9 MB 4.4 MB/s eta 0:00:03
   ---- ----------------------------------- 1.1/9.9 MB 4.7 MB/s eta 0:00:02
   ----- ---------------------------------- 1.3/9.9 MB 4.7 MB/s eta 0:00:02
   ------ --------------------------------- 1.6/9.9 MB 4.6 MB/s eta 0:00:02
   ------- -------------------------------- 1.8/9.9 MB 4.6 MB/s eta 0:00:02
   -------- ------------------------------- 2.1/9.9 MB 4.9 MB/s eta 0:00:02
   --------- ------------------------------ 2.3/9.9 MB 4.8 MB/s eta 0:00:02
   ---------- ----------------------------- 2.5/9.9 MB 4.9 MB/s eta 0:00:02
   ---------- ----------------------------- 2.7/9.9 MB 4.8 MB/s eta 0:00:02
   ------------ --------------------------- 3.0/9.9 MB 4.9 MB/s eta 0:00:02
   ------------ --------------------------- 3.2/9.9 MB 4.9 MB/s eta 0:00:02
   -------------- ------------------------- 3.5/9.9 MB 4.8 MB/s eta 0:00:02
   --------------- ------------------------ 3.8/9.9 MB 4.9 MB/s eta 0:00:02
   ---------------- ----------------------- 4.2/9.9 MB 5.0 MB/s eta 0:00:02
   ------------------ --------------------- 4.5/9.9 MB 5.0 MB/s eta 0:00:02
   ------------------ --------------------- 4.7/9.9 MB 5.0 MB/s eta 0:00:02
   -------------------- ------------------- 5.0/9.9 MB 5.0 MB/s eta 0:00:01
   --------------------- ------------------ 5.3/9.9 MB 5.0 MB/s eta 0:00:01
   ---------------------- ----------------- 5.5/9.9 MB 5.0 MB/s eta 0:00:01
   ----------------------- ---------------- 5.8/9.9 MB 5.0 MB/s eta 0:00:01
   ------------------------ --------------- 6.0/9.9 MB 5.1 MB/s eta 0:00:01
   ------------------------- -------------- 6.3/9.9 MB 5.1 MB/s eta 0:00:01
   -------------------------- ------------- 6.6/9.9 MB 5.1 MB/s eta 0:00:01
   --------------------------- ------------ 6.8/9.9 MB 5.0 MB/s eta 0:00:01
   ---------------------------- ----------- 7.0/9.9 MB 5.1 MB/s eta 0:00:01
   ---------------------------- ----------- 7.1/9.9 MB 5.0 MB/s eta 0:00:01
   ----------------------------- ---------- 7.4/9.9 MB 5.0 MB/s eta 0:00:01
   ------------------------------ --------- 7.7/9.9 MB 5.0 MB/s eta 0:00:01
   ------------------------------- -------- 7.8/9.9 MB 4.9 MB/s eta 0:00:01
   -------------------------------- ------- 8.0/9.9 MB 4.9 MB/s eta 0:00:01
   --------------------------------- ------ 8.3/9.9 MB 4.9 MB/s eta 0:00:01
   ---------------------------------- ----- 8.5/9.9 MB 4.9 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.9 MB 4.9 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.9 MB 4.9 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 4.9 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 4.5 MB/s eta 0:00:00
Downloading matplotlib-3.10.9-cp311-cp311-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.2/8.2 MB 4.9 MB/s eta 0:00:02
   -- ------------------------------------- 0.5/8.2 MB 5.6 MB/s eta 0:00:02
   --- ------------------------------------ 0.7/8.2 MB 5.2 MB/s eta 0:00:02
   ---- ----------------------------------- 0.9/8.2 MB 5.3 MB/s eta 0:00:02
   ---- ----------------------------------- 1.0/8.2 MB 4.9 MB/s eta 0:00:02
   ------ --------------------------------- 1.3/8.2 MB 4.7 MB/s eta 0:00:02
   ------ --------------------------------- 1.4/8.2 MB 4.5 MB/s eta 0:00:02
   -------- ------------------------------- 1.8/8.2 MB 4.5 MB/s eta 0:00:02
   ---------- ----------------------------- 2.2/8.2 MB 4.6 MB/s eta 0:00:02
   ------------ --------------------------- 2.5/8.2 MB 4.8 MB/s eta 0:00:02
   ------------- -------------------------- 2.8/8.2 MB 4.8 MB/s eta 0:00:02
   -------------- ------------------------- 3.0/8.2 MB 4.8 MB/s eta 0:00:02
   --------------- ------------------------ 3.1/8.2 MB 4.7 MB/s eta 0:00:02
   --------------- ------------------------ 3.1/8.2 MB 4.7 MB/s eta 0:00:02
   ----------------- ---------------------- 3.6/8.2 MB 4.7 MB/s eta 0:00:01
   ------------------ --------------------- 3.9/8.2 MB 4.8 MB/s eta 0:00:01
   -------------------- ------------------- 4.1/8.2 MB 4.9 MB/s eta 0:00:01
   --------------------- ------------------ 4.4/8.2 MB 4.9 MB/s eta 0:00:01
   ---------------------- ----------------- 4.6/8.2 MB 4.9 MB/s eta 0:00:01
   ----------------------- ---------------- 4.7/8.2 MB 4.9 MB/s eta 0:00:01
   ----------------------- ---------------- 4.7/8.2 MB 4.9 MB/s eta 0:00:01
   ------------------------ --------------- 5.1/8.2 MB 4.7 MB/s eta 0:00:01
   ------------------------- -------------- 5.3/8.2 MB 4.7 MB/s eta 0:00:01
   -------------------------- ------------- 5.4/8.2 MB 4.7 MB/s eta 0:00:01
   --------------------------- ------------ 5.6/8.2 MB 4.5 MB/s eta 0:00:01
   ---------------------------- ----------- 5.8/8.2 MB 4.6 MB/s eta 0:00:01
   ----------------------------- ---------- 6.0/8.2 MB 4.6 MB/s eta 0:00:01
   ------------------------------ --------- 6.3/8.2 MB 4.6 MB/s eta 0:00:01
   -------------------------------- ------- 6.6/8.2 MB 4.6 MB/s eta 0:00:01
   --------------------------------- ------ 6.8/8.2 MB 4.6 MB/s eta 0:00:01
   ---------------------------------- ----- 7.1/8.2 MB 4.7 MB/s eta 0:00:01
   ----------------------------------- ---- 7.3/8.2 MB 4.7 MB/s eta 0:00:01
   ------------------------------------ --- 7.5/8.2 MB 4.7 MB/s eta 0:00:01
   ------------------------------------- -- 7.8/8.2 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------  8.0/8.2 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------  8.2/8.2 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------  8.2/8.2 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------  8.2/8.2 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------  8.2/8.2 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------  8.2/8.2 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------  8.2/8.2 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 4.0 MB/s eta 0:00:00
Downloading contourpy-1.3.3-cp311-cp311-win_amd64.whl (225 kB)
   ---------------------------------------- 0.0/225.2 kB ? eta -:--:--
   ------------------------------------ --- 204.8/225.2 kB 6.3 MB/s eta 0:00:01
   -------------------------------------- - 215.0/225.2 kB 4.4 MB/s eta 0:00:01
   ---------------------------------------- 225.2/225.2 kB 2.3 MB/s eta 0:00:00
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.62.1-cp311-cp311-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   -- ------------------------------------- 0.1/2.3 MB 4.3 MB/s eta 0:00:01
   ----- ---------------------------------- 0.3/2.3 MB 4.1 MB/s eta 0:00:01
   --------- ------------------------------ 0.6/2.3 MB 4.4 MB/s eta 0:00:01
   -------------- ------------------------- 0.8/2.3 MB 4.8 MB/s eta 0:00:01
   ------------------ --------------------- 1.1/2.3 MB 4.9 MB/s eta 0:00:01
   ----------------------- ---------------- 1.4/2.3 MB 5.1 MB/s eta 0:00:01
   --------------------------- ------------ 1.6/2.3 MB 5.2 MB/s eta 0:00:01
   -------------------------------- ------- 1.9/2.3 MB 5.2 MB/s eta 0:00:01
   ------------------------------------ --- 2.1/2.3 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------  2.3/2.3 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 2.3/2.3 MB 4.7 MB/s eta 0:00:00
Downloading kiwisolver-1.5.0-cp311-cp311-win_amd64.whl (73 kB)
   ---------------------------------------- 0.0/73.5 kB ? eta -:--:--
   ---------------------------------------- 73.5/73.5 kB 4.2 MB/s eta 0:00:00
Downloading pillow-12.2.0-cp311-cp311-win_amd64.whl (7.1 MB)
   ---------------------------------------- 0.0/7.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.1 MB 5.9 MB/s eta 0:00:02
   --- ------------------------------------ 0.6/7.1 MB 5.9 MB/s eta 0:00:02
   ---- ----------------------------------- 0.8/7.1 MB 5.8 MB/s eta 0:00:02
   ------ --------------------------------- 1.1/7.1 MB 5.8 MB/s eta 0:00:02
   ------- -------------------------------- 1.3/7.1 MB 5.7 MB/s eta 0:00:02
   --------- ------------------------------ 1.6/7.1 MB 5.6 MB/s eta 0:00:01
   ----------- ---------------------------- 2.0/7.1 MB 5.6 MB/s eta 0:00:01
   -------------- ------------------------- 2.5/7.1 MB 5.7 MB/s eta 0:00:01
   --------------- ------------------------ 2.8/7.1 MB 5.7 MB/s eta 0:00:01
   ----------------- ---------------------- 3.0/7.1 MB 5.2 MB/s eta 0:00:01
   -------------------- ------------------- 3.6/7.1 MB 5.4 MB/s eta 0:00:01
   ---------------------- ----------------- 4.0/7.1 MB 5.3 MB/s eta 0:00:01
   ------------------------- -------------- 4.4/7.1 MB 5.4 MB/s eta 0:00:01
   -------------------------- ------------- 4.7/7.1 MB 5.4 MB/s eta 0:00:01
   --------------------------- ------------ 4.9/7.1 MB 5.4 MB/s eta 0:00:01
   ----------------------------- ---------- 5.2/7.1 MB 5.5 MB/s eta 0:00:01
   ------------------------------- -------- 5.5/7.1 MB 5.5 MB/s eta 0:00:01
   -------------------------------- ------- 5.8/7.1 MB 5.5 MB/s eta 0:00:01
   ---------------------------------- ----- 6.1/7.1 MB 5.5 MB/s eta 0:00:01
   ----------------------------------- ---- 6.3/7.1 MB 5.5 MB/s eta 0:00:01
   ------------------------------------- -- 6.6/7.1 MB 5.5 MB/s eta 0:00:01
   -------------------------------------- - 6.8/7.1 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------  7.0/7.1 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------- 7.1/7.1 MB 5.3 MB/s eta 0:00:00
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
   ---------------------------------------- 0.0/122.8 kB ? eta -:--:--
   ---------------------------------------- 122.8/122.8 kB 3.6 MB/s eta 0:00:00
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
   ---------------------------------------- 0.0/349.3 kB ? eta -:--:--
   -------------------------------------- - 337.9/349.3 kB 7.0 MB/s eta 0:00:01
   ---------------------------------------- 349.3/349.3 kB 4.3 MB/s eta 0:00:00
Installing collected packages: tzdata, pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, pandas, matplotlib
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.62.1 kiwisolver-1.5.0 matplotlib-3.10.9 pandas-3.0.2 pillow-12.2.0 pyparsing-3.3.2 tzdata-2026.2
Note: you may need to restart the kernel to use updated packages.

  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'c:\Users\ASUS\AppData\Local\Programs\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

In [8]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("../data/kg_train.csv",encoding='latin-1')

# Reduce the training set to speed up development. 
# Modify for final system
data = data.head(1000)
print(data.shape)
data.fillna("",inplace=True)

(1000, 2)

                                                  text  label
0    DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...      1
1                                             Will do.      0
2    Nora--Cheryl has emailed dozens of memos about...      0
3    Dear Sir=2FMadam=2C I know that this proposal ...      1
4                                                  fyi      0
..                                                 ...    ...
995  So what's the latest? It sounds contradictory ...      0
996  TRANSFER OF 36,759,000.00 MILLION POUNDS TO YO...      1
997  Barb I will call to explain. Are you back in t...      0
998    Yang on travelNot free tonite.May work tomorrow      0
999  sbwhoeopSunday February 21 2010 7:42 PMHShaunH...      0

[1000 rows x 2 columns]

### Let's divide the training and test set into two partitions

In [10]:
print(data.columns)

Index(['text', 'label'], dtype='str')

In [11]:
from sklearn.model_selection import train_test_split

X = data.drop(columns=["label"])
y = data["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(800, 1) (200, 1)
(800,) (200,)

## Data Preprocessing

In [12]:
import string
from nltk.corpus import stopwords
print(string.punctuation)
print(stopwords.words("english")[100:110])
from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer('english')

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [22]:
import re

def remove_html_code(text):
    text = str(text)

    # Removing inline JavaScript blocks: <script> ... </script>:
    text = re.sub(r"<script.*?>.*?</script>", " ", text, flags=re.DOTALL | re.IGNORECASE)

    # Removing inline CSS/style blocks: <style> ... </style>:
    text = re.sub(r"<style.*?>.*?</style>", " ", text, flags=re.DOTALL | re.IGNORECASE)

    # Removing HTML comments: <!-- comment -->
    # This is done before removing regular tags because comments may contain > characters:
    text = re.sub(r"<!--.*?-->", " ", text, flags=re.DOTALL)

    # Removing remaining HTML tags such as <p>, <a>, <br>, <div>:
    text = re.sub(r"<[^>]+>", " ", text)

    return text

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

In [25]:
import string

# Removing noisy characters and standardising the text:

def clean_text_basic(text):
    text = str(text)

    # Removing all special characters and punctuation
    text = re.sub(f"[{re.escape(string.punctuation)}]", " ", text)

    # Removing numbers
    text = re.sub(r'\d+', ' ', text)

    # Removing all single characters
    text = re.sub(r'\b[a-zA-Z]\b', ' ', text)

    # Removing single characters from the start
    text = re.sub(r'^[a-zA-Z]\s+', ' ', text)

    # Removing prefix lowercase b, often from byte strings like b'hello'
    text = re.sub(r"^b\s+", " ", text)

    # Substituting multiple spaces with one space
    text = re.sub(r'\s+', ' ', text)

    # Converting to lowercase
    text = text.lower()

    # Removing leading/trailing spaces
    text = text.strip()

    return text

In [26]:
X_train_no_html = X_train.apply(remove_html_code)
X_test_no_html = X_test.apply(remove_html_code)

In [27]:
X_train_clean = X_train_no_html.apply(clean_text_basic)
X_test_clean = X_test_no_html.apply(clean_text_basic)

In [28]:
print(X_train.iloc[0])
print("----- After HTML cleaning -----")
print(X_train_no_html.iloc[0])
print("----- After Basic cleaning -----")
print(X_train_clean.iloc[0])

text    Dear=2C Good day hope fine=2Cdear am writting ...
Name: 442, dtype: str
----- After HTML cleaning -----
442    Dear=2C Good day hope fine=2Cdear am writting ...
962    FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...
971                                             Will do.
190    FROM THE DESK OF DR.ADAMU  ISMALERAUDITING AND...
551    Dear Friend, My name is LOI C.ESTRADA,The wife...
                             ...
625       Dear, &nbsp;  It is my ple...
728    Will do. Think we are in good shape. Immelt In...
664    With your permission we are changing the state...
798                      Yes we will. Thank you Courtney
Name: text, Length: 800, dtype: str
----- After Basic cleaning -----
dear good day hope fine cdear am writting from mr henry kaborethe chief auditor incharge will do from the desk of dr adamu ismalerauditing and dear friend my name is loi estrada the wife dear nbsp it is my ple will do think we are in good shape immelt in with your permission we are changing the state yes we will thank you courtney name text length dtype str

## Now let's work on removing stopwords
Remove the stopwords.

In [29]:
import nltk
from nltk.corpus import stopwords

# Download stopwords list if needed
nltk.download("stopwords")

# Load English stopwords
stop_words = set(stopwords.words("english"))

def remove_stopwords(text):
    words = text.split()
    words_no_stopwords = [word for word in words if word not in stop_words]
    return " ".join(words_no_stopwords)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [30]:
X_train_no_stopwords = X_train_clean.apply(remove_stopwords)
X_test_no_stopwords = X_test_clean.apply(remove_stopwords)

In [31]:
print(X_train_clean.iloc[0])
print("----- WITHOUT STOPWORDS -----")
print(X_train_no_stopwords.iloc[0])

dear good day hope fine cdear am writting from mr henry kaborethe chief auditor incharge will do from the desk of dr adamu ismalerauditing and dear friend my name is loi estrada the wife dear nbsp it is my ple will do think we are in good shape immelt in with your permission we are changing the state yes we will thank you courtney name text length dtype str
----- WITHOUT STOPWORDS -----
dear good day hope fine cdear writting mr henry kaborethe chief auditor incharge desk dr adamu ismalerauditing dear friend name loi estrada wife dear nbsp ple think good shape immelt permission changing state yes thank courtney name text length dtype str

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [32]:
from nltk.stem import WordNetLemmatizer

nltk.download("wordnet")
nltk.download("omw-1.4")

lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    words = text.split()
    lemmatized_words = [lemmatizer.lemmatize(word) for word in words]
    return " ".join(lemmatized_words)

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...

In [33]:
X_train_lemmatized = X_train_no_stopwords.apply(lemmatize_text)
X_test_lemmatized = X_test_no_stopwords.apply(lemmatize_text)

In [34]:
print(X_train_no_stopwords.iloc[0])
print("----- LEMMATIZED -----")
print(X_train_lemmatized.iloc[0])

dear good day hope fine cdear writting mr henry kaborethe chief auditor incharge desk dr adamu ismalerauditing dear friend name loi estrada wife dear nbsp ple think good shape immelt permission changing state yes thank courtney name text length dtype str
----- LEMMATIZED -----
dear good day hope fine cdear writting mr henry kaborethe chief auditor incharge desk dr adamu ismalerauditing dear friend name loi estrada wife dear nbsp ple think good shape immelt permission changing state yes thank courtney name text length dtype str

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [ ]:
from collections import Counter
import pandas as pd

# Combining the cleaned/lemmatized training text with the training labels.
# reset_index(drop=True) makes sure both Series align row by row.
eda_data = pd.DataFrame({
    "text": X_train_lemmatized.reset_index(drop=True),
    "label": y_train.reset_index(drop=True)
})

# Quick check
print(eda_data.head())
print(eda_data["label"].value_counts())

                                                text  label
0  dear good day hope fine cdear writting mr henr...      1
1                                                NaN      1
2                                                NaN      0
3                                                NaN      1
4                                                NaN      1
label
0    446
1    354
Name: count, dtype: int64

In [38]:
# Making sure text is string and missing values are removed/replaced:
eda_data["text"] = eda_data["text"].fillna("").astype(str)

# Separating messages by class:
ham_messages = eda_data[eda_data["label"] == 0]["text"]
spam_messages = eda_data[eda_data["label"] == 1]["text"]

# Joining all messages in each class into one long string:
ham_text = " ".join(ham_messages)
spam_text = " ".join(spam_messages)

In [39]:
print(type(ham_text))
print(type(spam_text))

print("Ham text sample:")
print(ham_text[:500])

print("\nSpam text sample:")
print(spam_text[:500])

<class 'str'>
<class 'str'>
Ham text sample:


Spam text sample:
dear good day hope fine cdear writting mr henry kaborethe chief auditor incharge desk dr adamu ismalerauditing dear friend name loi estrada wife dear nbsp ple think good shape immelt permission changing state yes thank courtney name text length dtype str

In [ ]:
from collections import Counter

# Counting word frequency for ham and spam
ham_word_counts = Counter(ham_text.split())
spam_word_counts = Counter(spam_text.split())

In [42]:
print("Number of ham words:", len(ham_text.split()))
print("Number of spam words:", len(spam_text.split()))

print("Top 10 ham words:")
print(ham_word_counts.most_common(10))

print("\nTop 10 spam words:")
print(spam_word_counts.most_common(10))

Number of ham words: 0
Number of spam words: 41
Top 10 ham words:
[]

Top 10 spam words:
[('dear', 3), ('good', 2), ('name', 2), ('day', 1), ('hope', 1), ('fine', 1), ('cdear', 1), ('writting', 1), ('mr', 1), ('henry', 1)]

## Extra features

In [ ]:
# Creating train and validation DataFrames using our cleaned/lemmatized text
data_train = pd.DataFrame({
    "preprocessed_text": X_train_lemmatized.reset_index(drop=True),
    "label": y_train.reset_index(drop=True)
})

data_val = pd.DataFrame({
    "preprocessed_text": X_test_lemmatized.reset_index(drop=True),
    "label": y_test.reset_index(drop=True)
})

In [ ]:
# Forcing every value to be text and removing missing-value problems:

data_train["preprocessed_text"] = data_train["preprocessed_text"].fillna("").astype(str)
data_val["preprocessed_text"] = data_val["preprocessed_text"].fillna("").astype(str)

# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data_train['money_mark'] = data_train['preprocessed_text'].str.contains(money_simbol_list, na = False)*1
data_train['suspicious_words'] = data_train['preprocessed_text'].str.contains(suspicious_words, na = False)*1
data_train['text_len'] = data_train['preprocessed_text'].apply(lambda x: len(x)) 

data_val['money_mark'] = data_val['preprocessed_text'].str.contains(money_simbol_list, na = False)*1
data_val['suspicious_words'] = data_val['preprocessed_text'].str.contains(suspicious_words, na = False)*1
data_val['text_len'] = data_val['preprocessed_text'].apply(lambda x: len(x)) 

data_train.head()

,preprocessed_text,label,money_mark,suspicious_words,text_len
0,dear good day hope fine cdear writting mr henr...,1,0,0,254
1,,1,0,0,0
2,,0,0,0,0
3,,1,0,0,0
4,,1,0,0,0

## How would work the Bag of Words with Count Vectorizer concept?

In [ ]:
# Applying the CountVectorizer concept:

from sklearn.feature_extraction.text import CountVectorizer

# Creating CountVectorizer
count_vectorizer = CountVectorizer()

# Fitting on training text and transforming training text into word-count vectors
X_train_count = count_vectorizer.fit_transform(data_train["preprocessed_text"])

# Transforming validation text using the vocabulary learned from training text
X_val_count = count_vectorizer.transform(data_val["preprocessed_text"])

# Quick check
print(X_train_count.shape)
print(X_val_count.shape)

(800, 37)
(200, 37)

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [48]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Create TF-IDF vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Fit on training text and transform training text into TF-IDF vectors
X_train_tfidf = tfidf_vectorizer.fit_transform(data_train["preprocessed_text"])

# Transform validation text using the vocabulary/weights learned from training text
X_val_tfidf = tfidf_vectorizer.transform(data_val["preprocessed_text"])

# Print the shape of the vectorized datasets
print(X_train_tfidf.shape)
print(X_val_tfidf.shape)

(800, 37)
(200, 37)

## And the Train a Classifier?

In [ ]:
from sklearn.linear_model import LogisticRegression

# Creating the classifier/model
classifier = LogisticRegression(max_iter=1000)

# Training the classifier on the training data
classifier.fit(X_train_tfidf, data_train["label"])

LogisticRegression(max_iter=1000)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Predicting labels for validation data
y_pred = classifier.predict(X_val_tfidf)

# Evaluating performance
print("Accuracy:", accuracy_score(data_val["label"], y_pred))
print("\nClassification report:")
print(classification_report(data_val["label"], y_pred))

print("\nConfusion matrix:")
print(confusion_matrix(data_val["label"], y_pred))

Accuracy: 0.565

Classification report:
              precision    recall  f1-score   support

           0       0.56      1.00      0.72       112
           1       1.00      0.01      0.02        88

    accuracy                           0.56       200
   macro avg       0.78      0.51      0.37       200
weighted avg       0.76      0.56      0.41       200


Confusion matrix:
[[112   0]
 [ 87   1]]

In [ ]:
# The model has basically learned how to predict almost everything as ham.

# That gives mediocre accuracy, but it fails the real goal, which is to detect spam.

# In summyary, acuracy alone is not enough. We need recall/F1 for spam detection too.

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).

In [ ]:
# Your code